{% set version = '1.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-webp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/webp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/webp/webp_{{ version }}.tar.gz
  sha256: 06ae1f069842f8287758fb2040fe40032740f7571f2ff0347e26b9e3203634a5

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('webp')"           # [not win]
    - "\"%R%\" -e \"library('webp')\""  # [win]

about:
  home: https://github.com/jeroen/webp https://developers.google.com/speed/webp
  license: MIT
  summary: Lossless webp images are 26% smaller in size compared to PNG. Lossy webp images are
    25-34% smaller in size compared to JPEG. This package reads and writes webp images
    into a 3 (rgb) or 4 (rgba) channel bitmap array using conventions from the 'jpeg'
    and 'png' packages.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

extra:
  recipe-maintainers:
    - conda-forge/r
    - abalter
